name: Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
      - run: ./gradlew build
      - uses: actions/upload-artifact@v1
    with:
      name: Package
      path: build/libs
      


        
