name: Generate artifact

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: initialize the gradle
        run: ./gradlew build
      - name: Run the Gradle package task
        run: ./gradlew -b ci.gradle package
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: build/libs
